name: "tf_validate"
on:
  workflow_call:

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CONTAINER_NAME: ${{ inputs.az_container_name }}
      STORAGE_ACCOUNT: ${{ inputs.az_storage_acc }}
      RESOURCE_GROUP: ${{ inputs.az_resource_group }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.arm_subscription_id }}
      ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.arm_client_secret }}
      ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
      TF_KEY: ${{ inputs.tf_key }}.tfstate
      TF_VARS: ${{ inputs.tf_vars_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ github.events.inputs.tf_version || 'latest' }}

      - name: Terraform Init
        id: init
        run: terraform init --backend-config="storage_account_name=$STORAGE_ACCOUNT" --backend-config="container_name=$CONTAINER_NAME" --backend-config="resource_group_name=$RESOURCE_GROUP" --backend-config="key=$TF_KEY"

      - name: Terraform Format
        id: fmt
        run: terraform fmt --check
      
      - name: Terraform Validate
        id: validate
        run: terraform validate